# Generated by Django 6.0.2 on 2026-03-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("description", models.CharField(max_length=150, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("description", models.CharField(max_length=150, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/products/images", verbose_name="Изображение"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Цена за покупку")),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                ("updated_at", models.DateField(verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        max_length=100,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["category", "name"],
            },
        ),
    ]
